name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request: {}

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      has_tag: ${{ steps.get_info.outputs.has_tag }}
      tag: ${{ steps.get_info.outputs.tag }}
    steps:
      - id: get_info
        run: |
          tag="${REF##*/}"
          echo "has_tag=$has_tag" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT
        env:
          REF: ${{ github.ref }}
          has_tag: ${{ startsWith(github.ref, 'refs/tags/') }}

  test:
    strategy:
      matrix:
        dc: [dmd-2.102.2, ldc-1.32.1]
        experimental: [false]
        include:
          - dc: dmd-master
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/cache@v3
        with:
          path: ~/.dub
          key: ${{ runner.os }}-dub-${{ matrix.dc }}-${{ hashFiles('**/dub.json') }}
          restore-keys: |
            ${{ runner.os }}-dub-${{ matrix.dc }}-test
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run tests
        run: dub -q test

  release:
    runs-on: ubuntu-latest
    needs: [info, test]
    if: github.event_name == 'push' && needs.info.outputs.has_tag == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: softprops/action-gh-release@v1
        id: create_release
